### ISSUE TITLE
when i try to train mot20, it has a error

### ISSUE THREAD

**Issue by muzishen** [ifzhang/FairMOT#10]
File "train.py", line 99, in <module>
    main(opt)
  File "train.py", line 70, in main
    log_dict_train, _ = trainer.train(epoch, train_loader)
  File "FairMOT/src/lib/trains/base_trainer.py", line 118, in train
    return self.run_epoch('train', epoch, data_loader)
  File "FairMOT/src/lib/trains/base_trainer.py", line 61, in run_epoch
    for iter_id, batch in enumerate(data_loader):
  File "/usr/local/app/anaconda3/envs/tracking/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 801, in __next__
    return self._process_data(data)
  File "/usr/local/app/anaconda3/envs/tracking/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/usr/local/app/anaconda3/envs/tracking/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 6.
Original Traceback (most recent call last):
  File "/usr/local/app/anaconda3/envs/tracking/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/app/anaconda3/envs/tracking/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/app/anaconda3/envs/tracking/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "FairMOT/src/lib/datasets/dataset/jde.py", line 460, in __getitem__
    wh[k] = 1. * w, 1. * h
IndexError: index 400 is out of bounds for axis 0 with size 400

can you help me ?

**Comment by ifzhang** [comment]
I change the max number of objects to opt.K of MOT20 in jde.py. It seems that you get more than 400 objects in an image and the max number is set 400, so it out of bounds. When training on MOT20, you should set --K 500, like in experiments/ft_mot20_dla34.sh. If it still cannot work, you may check whether you process the dataset of MOT20 correctly.

**Comment by muzishen** [comment]
@ifzhang   First, thank for your reply ! 
But l don not change 'experiments/ft_mot20_dla34.sh' and K is default set 500.  
Second,  the weights   of experiments/ft_mot20_dla34.sh  are trained  based on MOT15  dataset?
Last,     ft_mot20_dla34.sh (MOT20)  is to continue training in the weight of MOT15.
I hope you can help me, thank you !

**Comment by ifzhang** [comment]
It does not continue training in the weight of MOT15, we train MOT20 in the weight of all_dla34.pth which is trained on the large training dataset.
