### ISSUE TITLE
error when  sh make.sh of  DCNv2_new or DCNv2

### ISSUE THREAD

**Issue by LrobotD** [ifzhang/FairMOT#154]
ubuntu 18.04/2080ti/python 3.7/pytorch 1.2/cudatoolkit 10.0./cudnn 7.6.5
all libs of the 'requirements.txt' were installed except  'lap'
when I did  FairMOT/src/lib/models/networks/DCNv2_new$ sh make.sh   
i got this:
running build
running build_ext
Traceback (most recent call last):
  File "setup.py", line 70, in <module>
    cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
  File "/home/luo/anaconda3/envs/fairmot/lib/python3.7/site-packages/setuptools/__init__.py", line 161, in setup
    return distutils.core.setup(**attrs)
  File "/home/luo/anaconda3/envs/fairmot/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/luo/anaconda3/envs/fairmot/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/luo/anaconda3/envs/fairmot/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/luo/anaconda3/envs/fairmot/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/luo/anaconda3/envs/fairmot/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/luo/anaconda3/envs/fairmot/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/luo/anaconda3/envs/fairmot/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/home/luo/anaconda3/envs/fairmot/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/luo/anaconda3/envs/fairmot/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/luo/anaconda3/envs/fairmot/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 237, in build_extensions
    self._check_abi()
  File "/home/luo/anaconda3/envs/fairmot/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 377, in _check_abi
    check_compiler_abi_compatibility(compiler)
  File "/home/luo/anaconda3/envs/fairmot/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 167, in check_compiler_abi_compatibility
    if not check_compiler_ok_for_platform(compiler):
  File "/home/luo/anaconda3/envs/fairmot/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 143, in check_compiler_ok_for_platform
    which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
  File "/home/luo/anaconda3/envs/fairmot/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/luo/anaconda3/envs/fairmot/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['which', 'g++']' returned non-zero exit status 1.

i don't know how to solve the problem, could you help me ,thanks!!!

**Comment by boy-new-2019** [comment]
not use pytorch=1.5， you can use pytorch=1.2 , it will works good

**Comment by LrobotD** [comment]
@boy-new-2019 ,thank you for your reply!!!  I have set it like i introduced before. I solved this problem by changing the CUDA version to 10.2 of the computer environment(not conda environment).
