### ISSUE TITLE
Found on NVIDIA driver on the system.

### ISSUE THREAD

**Issue by SINHAPIYUSH** [ifzhang/FairMOT#161]
Hi,
I am facing an error while following the steps mention in the readme.

When I try to run the demo command below:
cd src
python demo.py mot --load_model ../models/all_dla34.pth --conf_thres 0.4

I am facing the below error:
python demo.py mot --load_model ../models/all_dla34.pth --conf_thres 0.4
Fix size testing.
training chunk_sizes: [6, 6]
The output will be saved to  /home/npu/Downloads/FAIRMOT_ROOT/src/lib/../../exp/mot/default
heads {'hm': 1, 'wh': 2, 'id': 512, 'reg': 2}
2020-06-23 09:36:20 [INFO]: Starting tracking...
Lenth of the video: 1500 frames
Creating model...
loaded ../models/all_dla34.pth, epoch 10
Traceback (most recent call last):
  File "demo.py", line 40, in <module>
    demo(opt)
  File "demo.py", line 30, in demo
    eval_seq(opt, dataloader, 'mot', result_filename, save_dir=frame_dir, show_image=False, frame_rate=frame_rate)
  File "/home/npu/Downloads/FAIRMOT_ROOT/src/track.py", line 51, in eval_seq
    tracker = JDETracker(opt, frame_rate=frame_rate)
  File "/home/npu/Downloads/FAIRMOT_ROOT/src/lib/tracker/multitracker.py", line 179, in __init__
    self.model = self.model.to(opt.device)
  File "/home/npu/anaconda3/envs/FairMOT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 432, in to
    return self._apply(convert)
  File "/home/npu/anaconda3/envs/FairMOT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/home/npu/anaconda3/envs/FairMOT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/home/npu/anaconda3/envs/FairMOT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/home/npu/anaconda3/envs/FairMOT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 230, in _apply
    param_applied = fn(param)
  File "/home/npu/anaconda3/envs/FairMOT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 430, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
  File "/home/npu/anaconda3/envs/FairMOT/lib/python3.7/site-packages/torch/cuda/__init__.py", line 178, in _lazy_init
    _check_driver()
  File "/home/npu/anaconda3/envs/FairMOT/lib/python3.7/site-packages/torch/cuda/__init__.py", line 99, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx

I am using:
VMware® Workstation 14 Pro
ubuntu-16.04.6-desktop-amd64

I want to run the model on CPU. I have enabled the option in opts.py as -1 for CPU. However I am still getting the above error.
Is anyone able to run it on CPU?

Thanks in advance.

**Comment by SINHAPIYUSH** [comment]
Never mind, solved the issue after changing 
file: tracker.py
line no: 61 ----------> blob = torch.from_numpy(img).cuda().unsqueeze(0)
to this ----------------> blob = torch.from_numpy(img).cpu().unsqueeze(0)

**Comment by yesh2007** [comment]
> Never mind, solved the issue after changing
> file: tracker.py
> line no: 61 ----------> blob = torch.from_numpy(img).cuda().unsqueeze(0)
> to this ----------------> blob = torch.from_numpy(img).cpu().unsqueeze(0)

Hi, am trying to implement it on CPU but not successful, getting stuck with DCNv2.
Any suggestions on how to take it up?

Thanks in advance.
