### ISSUE TITLE
AssertionError: Invalid device id

### ISSUE THREAD

**Issue by sagarkarki136** [ifzhang/FairMOT#162]
I am facing 2 problems
I want to change the number of classes and I am not able to find the varible associated with it
        I tried opt.num_classes but it again sets itself to 1 

second is:  AssertionError: Invalid device id

Starting training...
Traceback (most recent call last):
  File "train.py", line 99, in <module>
    main(opt)
  File "train.py", line 66, in main
    trainer.set_device(opt.gpus, opt.chunk_sizes, opt.device)
  File "/content/rrr/src/lib/trains/base_trainer.py", line 36, in set_device
    chunk_sizes=chunk_sizes).to(device)
  File "/content/rrr/src/lib/models/data_parallel.py", line 127, in DataParallel               #I set the name of clone folder as rrr in colab
    return torch.nn.DataParallel(module, device_ids, output_device, dim)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 133, in __init__
    _check_balance(self.device_ids)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 19, in _check_balance
    dev_props = [torch.cuda.get_device_properties(i) for i in device_ids]
  File "/usr/local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 19, in <listcomp>
    dev_props = [torch.cuda.get_device_properties(i) for i in device_ids]
  File "/usr/local/lib/python3.6/site-packages/torch/cuda/__init__.py", line 318, in get_device_properties
    raise AssertionError("Invalid device id")
AssertionError: Invalid device id

**Comment by NaifahNurya** [comment]
Look on this issue, it will be helpful
https://github.com/ifzhang/FairMOT/issues/98
