### ISSUE TITLE
ModuleNotFoundError: No module named '_ext'

### ISSUE THREAD

**Issue by brianbarbieri** [ifzhang/FairMOT#186]
When I run the code:
` sh experiments/all_dla34.sh`
I get the following error:
`Traceback (most recent call last):
  File "train.py", line 14, in <module>
    from models.model import create_model, load_model, save_model
  File "/home/pats/Documents/models/FairMOT/src/lib/models/model.py", line 8, in <module>
    from .networks.pose_dla_dcn import get_pose_net as get_dla_dcn
  File "/home/pats/Documents/models/FairMOT/src/lib/models/networks/pose_dla_dcn.py", line 15, in <module>
    from .DCNv2.dcn_v2 import DCN
  File "/home/pats/Documents/models/FairMOT/src/lib/models/networks/DCNv2/dcn_v2.py", line 13, in <module>
    import _ext as _backend
ModuleNotFoundError: No module named '_ext'
`

Did anyone already face this issue and how was it solved?

**Comment by brianbarbieri** [comment]
I found out it probably has to do with the sh. make.sh

If I do that it gives the following error:

`/usr/include/c++/6/type_traits:1558:8: note: provided for ‘template<class _From, class _To> struct std::is_convertible’
     struct is_convertible
        ^~~~~~~~~~~~~~
/usr/include/c++/6/tuple:502:1: error: body of constexpr function ‘static constexpr bool std::_TC<<anonymous>, _Elements>::_NonNestedTuple() [with _SrcTuple = std::tuple<at::Tensor&, at::Tensor&, at::Tensor&>&&; bool <anonymous> = true; _Elements = {at::Tensor&, at::Tensor&, at::Tensor&}]’ not a return-statement
`

[The full error log can be found here](https://pastebin.com/DgeCaRN9)

Does anyone know what the problem is?

**Comment by brianbarbieri** [comment]
Solved by downgrading/upgrading to CUDA Version 10.2.89.
