### ISSUE TITLE
ModuleNotFoundError: No module named 'models.decode'

### ISSUE THREAD

**Issue by fraserprice** [ifzhang/FairMOT#193]
I am getting a ModuleNotFoundError while trying to run `demo.py`. I followed the installation steps, so am not sure why this is happening. Full trace:

```
Traceback (most recent call last):
  File "demo.py", line 14, in <module>
    from track import eval_seq
  File "/home/object-tracking/src/track.py", line 15, in <module>
    from tracker.multitracker import JDETracker
  File "/home/object-tracking/src/lib/tracker/multitracker.py", line 7, in <module>
    from models.decode import mot_decode
ModuleNotFoundError: No module named 'models.decode'
```

**Comment by ashwath1295** [comment]
Hello @fraserprice did you find the solution?

**Comment by lihuining** [comment]
I find it useful to add __init__.py in models such that models can be import.
