### ISSUE TITLE
No module named 'Cython' while installing requirements

### ISSUE THREAD

**Issue by Ursanon** [ifzhang/FairMOT#206]
I want to try FairMOT, but `pip install -r requirements.txt` gave me:

```
ERROR: Command errored out with exit status 1:
     command: /home/bk/anaconda3/envs/FairMOT/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-h7axnaxq/cython-bbox/setup.py'"'"'; __file__='"'"'/tmp/pip-install-h7axnaxq/cython-bbox/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-qqfmo6pi
         cwd: /tmp/pip-install-h7axnaxq/cython-bbox/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-h7axnaxq/cython-bbox/setup.py", line 10, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by Ursanon** [comment]
Solved by using
`pip install cython`, then 
`pip install cython-bbox`
