### ISSUE TITLE
EOFError: Ran out of input   help me!

### ISSUE THREAD

**Issue by qifyin** [ifzhang/FairMOT#209]
When I run the demo.py, I faced a problem: EOFError: Ran out of input .   Please tell me what can i do.  Traceback is as follows:

sudo python demo.py mot --load_model /home/qfy/FairMOT-master/models/all_dla34.pth --conf_thres 0.4

Fix size testing.
training chunk_sizes: [6, 6]
The output will be saved to  /home/qfy/FairMOT-master/src/lib/../../exp/mot/default
heads {'hm': 1, 'wh': 2, 'id': 512, 'reg': 2}
2020-08-04 14:26:25 [INFO]: Starting tracking...
Lenth of the video: 1500 frames
Creating model...
Traceback (most recent call last):
  File "demo.py", line 40, in <module>
    demo(opt)
  File "demo.py", line 30, in demo
    eval_seq(opt, dataloader, 'mot', result_filename, save_dir=frame_dir, show_image=False, frame_rate=frame_rate)
  File "/home/qfy/FairMOT-master/src/track.py", line 51, in eval_seq
    tracker = JDETracker(opt, frame_rate=frame_rate)
  File "/home/qfy/FairMOT-master/src/lib/tracker/multitracker.py", line 178, in __init__
    self.model = load_model(self.model, opt.load_model)
  File "/home/qfy/FairMOT-master/src/lib/models/model.py", line 31, in load_model
    checkpoint = torch.load(model_path, map_location=lambda storage, loc: storage)
  File "/home/qfy/.conda/envs/py37/lib/python3.7/site-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/qfy/.conda/envs/py37/lib/python3.7/site-packages/torch/serialization.py", line 563, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

**Comment by ifzhang** [comment]
I think the all_dla34.pth model is not correctly downloaded. You can try download it again.
