### ISSUE TITLE
I got a key error while training

### ISSUE THREAD

**Issue by astrayne** [ifzhang/FairMOT#242]
I got a key error while training.
KeyError: Caught KeyError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/FairMOT/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/FairMOT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/FairMOT/src/lib/trains/base_trainer.py", line 20, in forward
    loss, loss_stats = self.loss(outputs, batch)
  File "/home/ubuntu/anaconda3/envs/FairMOT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/FairMOT/src/lib/trains/mot.py", line 49, in forward
    mask_weight = batch['dense_wh_mask'].sum() + 1e-4
KeyError: 'dense_wh_mask'

How can I fix this error?

**Comment by ifzhang** [comment]
I have updated the code. We do not use 'dense_wh_mask' in this code.

**Comment by astrayne** [comment]
Thanks!
