### ISSUE TITLE
gpu

### ISSUE THREAD

**Issue by henbucuoshanghai** [ifzhang/FairMOT#245]
ile "/home/fengmap/FairMOT/DCNv2/dcn_v2.py", line 31, in forward
    ctx.deformable_groups)
RuntimeError: Not compiled with GPU support (dcn_v2_forward at /home/fengmap/FairMOT/DCNv2/src/dcn_v2.h:35)
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6d (0x7fa74f6f41cd in /home/fengmap/anaconda3/envs/FairMOT/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: dcn_v2_forward(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, int, int, int, int, int, int, int, int, int) + 0x1d4 (0x7fa7135b2b84 in /home/fengmap/FairMOT/DCNv2/_ext.cpython-37m-x86_64-linux-gnu.so)
frame #2: <unknown function> + 0x1868b (0x7fa7135c068b in /home/fengmap/FairMOT/DCNv2/_ext.cpython-37m-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x15157 (0x7fa7135bd157 in /home/fengmap/FairMOT/DCNv2/_ext.cpython-37m-x86_64-linux-gnu.so)
<omitting python frames>
frame #8: THPFunction_apply(_object*, _object*) + 0xa56 (0x7fa771fb75f6 in /home/fengmap/anaconda3/envs/FairMOT/lib/python3.7/site-packages/torch/lib/libtorch_python.so)

**Comment by henbucuoshanghai** [comment]
demo的时候  出现的   请问怎么回事

**Comment by ifzhang** [comment]
It seems that you do not compile DCNv2 successfully. You should compile DCNv2 first.

**Comment by xiaoaliu** [comment]
Installed /home/lee/FairMOT1/DCNv2
Processing dependencies for DCNv2==0.1
Finished processing dependencies for DCNv2==0.1
2021-09-20 10:58:35 [INFO]: Processing frame 0 (100000.00 fps)
Traceback (most recent call last):
  File "demo.py", line 43, in <module>
    demo(opt)
  File "demo.py", line 30, in demo
    eval_seq(opt, dataloader, 'mot', result_filename,
  File "/home/lee/FairMOT1/src/track.py", line 90, in eval_seq
    online_targets = tracker.update(blob, img0)
  File "/home/lee/FairMOT1/src/lib/tracker/multitracker.py", line 243, in update
    output = self.model(im_blob)[-1]
  File "/home/lee/anaconda3/envs/FairMOT/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lee/FairMOT1/src/lib/models/networks/pose_dla_dcn.py", line 472, in forward
    x = self.dla_up(x)
  File "/home/lee/anaconda3/envs/FairMOT/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lee/FairMOT1/src/lib/models/networks/pose_dla_dcn.py", line 411, in forward
    ida(layers, len(layers) -i - 2, len(layers))
  File "/home/lee/anaconda3/envs/FairMOT/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lee/FairMOT1/src/lib/models/networks/pose_dla_dcn.py", line 384, in forward
    layers[i] = upsample(project(layers[i]))
  File "/home/lee/anaconda3/envs/FairMOT/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lee/FairMOT1/src/lib/models/networks/pose_dla_dcn.py", line 355, in forward
    x = self.conv(x)
  File "/home/lee/anaconda3/envs/FairMOT/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lee/FairMOT1/DCNv2/dcn_v2.py", line 161, in forward
    return dcn_v2_conv(
  File "/home/lee/FairMOT1/DCNv2/dcn_v2.py", line 23, in forward
    output = _backend.dcn_v2_forward(
RuntimeError: Not compiled with GPU support

**Comment by xiaoaliu** [comment]
请问下 显示我已成功编译DCN 为什么还是没有GPU
