### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/data'

### ISSUE THREAD

**Issue by Hu-nie** [ifzhang/FairMOT#256]
(FairMOT) ubuntu@nipa2020-0949:~/FairMOT/src$ python track.py mot --load_model ../models/fairmot_dla34.pth --conf_thres 0.6
Fix size testing.
training chunk_sizes: [6, 6]
The output will be saved to  /home/ubuntu/FairMOT/src/lib/../../exp/mot/default
heads {'hm': 1, 'wh': 4, 'id': 128, 'reg': 2}
Traceback (most recent call last):
  File "track.py", line 278, in <module>
    save_videos=False)
  File "track.py", line 121, in main
    mkdir_if_missing(result_root)
  File "/home/ubuntu/FairMOT/src/lib/tracking_utils/utils.py", line 21, in mkdir_if_missing
    os.makedirs(d)
  File "/home/ubuntu/anaconda3/envs/FairMOT/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/ubuntu/anaconda3/envs/FairMOT/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/ubuntu/anaconda3/envs/FairMOT/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 6 more times]
  File "/home/ubuntu/anaconda3/envs/FairMOT/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/data'
(FairMOT) ubuntu@nipa2020-0949:~/FairMOT/src$

**### What is the reason?**

**Comment by jlu-lizab** [comment]
Hey, man. Maybe you should redo the data preparation section .
![image](https://user-images.githubusercontent.com/12468586/95534632-ea388e80-0a18-11eb-962e-66a6ad135403.png)

**Comment by Hu-nie** [comment]
I'll check

Thanks

**Comment by hsauod** [comment]
@Hu-nie hello Mr Hu, did you fix it?
I face the same trouble, could you please tell me how did you fix it?
Thank you very much.
