### ISSUE TITLE
RuntimeError: cuda runtime error (63) : OS call failed or operation not sed on this OS at /opt/conda/conda-bld/pytorch_1565272271120/work/aten/srcHCGeneral.cpp:50

### ISSUE THREAD

**Issue by SanumNisar** [ifzhang/FairMOT#300]
When im executing the demo command "python demo.py mot --load_model ../models/fairmot_dla34.pth --conf_thres 0.4
" im getting this run time error.

```
 loaded ../models/fairmot_dla34.pth, epoch 30

THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1565272271120/work/ateTHC/THCGeneral.cpp line=50 error=63 : OS call failed or operation not sup on this OS
Traceback (most recent call last):
  File "demo.py", line 58, in <module>
    demo(opt)
  File "demo.py", line 46, in demo
    save_dir=frame_dir, show_image=False, frame_rate=frame_rate)
  File "/lustre1/home/sanamn/Project/FairMOT/src/track.py", line 80, in eq
    tracker = JDETracker(opt, frame_rate=frame_rate)
  File "/lustre1/home/sanamn/Project/FairMOT/src/lib/tracker/multitrackerline 185, in __init__
    self.model = self.model.to(opt.device)
  File "/home/sanamn/miniconda3/envs/FairMOT/lib/python3.7/site-packages/nn/modules/module.py", line 432, in to
    return self._apply(convert)
  File "/home/sanamn/miniconda3/envs/FairMOT/lib/python3.7/site-packages/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/home/sanamn/miniconda3/envs/FairMOT/lib/python3.7/site-packages/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/home/sanamn/miniconda3/envs/FairMOT/lib/python3.7/site-packages/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/home/sanamn/miniconda3/envs/FairMOT/lib/python3.7/site-packages/nn/modules/module.py", line 230, in _apply
    param_applied = fn(param)
  File "/home/sanamn/miniconda3/envs/FairMOT/lib/python3.7/site-packages/nn/modules/module.py", line 430, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blo
  File "/home/sanamn/miniconda3/envs/FairMOT/lib/python3.7/site-packages/cuda/__init__.py", line 179, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (63) : OS call failed or operation not sed on this OS at /opt/conda/conda-bld/pytorch_1565272271120/work/aten/srcHCGeneral.cpp:50
```

Has anyone came across the similar issue? please help

**Comment by liluoqinchuan** [comment]
Hello, I entcountered  a similar problem. Have you solved this problem?
