### ISSUE TITLE
KeyError: 'epoch'

### ISSUE THREAD

**Issue by bhumikasinghrk** [ifzhang/FairMOT#311]
When i run 
!python demo.py mot --load_model ./lib/models/fairmot_dla34.pth --conf_thres 0.4

Fix size testing.
training chunk_sizes: [6, 6]
The output will be saved to  /content/gdrive/My Drive/FairMOT/src/lib/../../exp/mot/default
heads {'hm': 1, 'wh': 4, 'id': 128, 'reg': 2}
2020-12-15 05:00:40 [INFO]: Starting tracking...
Lenth of the video: 1500 frames
Creating model...
Traceback (most recent call last):
  File "demo.py", line 43, in <module>
    demo(opt)
  File "demo.py", line 32, in demo
    use_cuda=opt.gpus!=[-1])
  File "/content/gdrive/My Drive/FairMOT/src/track.py", line 73, in eval_seq
    tracker = JDETracker(opt, frame_rate=frame_rate)
  File "/content/gdrive/My Drive/FairMOT/src/lib/tracker/multitracker.py", line 184, in __init__
    self.model = load_model(self.model, opt.load_model)
  File "/content/gdrive/My Drive/FairMOT/src/lib/models/model.py", line 38, in load_model
    print('loaded {}, epoch {}'.format(model_path, checkpoint['epoch']))
KeyError: 'epoch'

**Comment by ifzhang** [comment]
You can check the path of file 'fairmot_dla34.pth'. I use this path: --load_model ../models/fairmot_dla34.pth

**Comment by mtmoreira98** [comment]
I have the same problem. 
Did you manage to solve?

**Comment by csdingithub** [comment]
当我跑hrnet模型的时候，出现了同样的问题，我的路径没有出错啊

**Comment by KeyuLuo** [comment]
> 当我跑hrnet模型的时候，出现了同样的问题，我的路径没有出错啊

请问您的这个问题解决了吗？我也遇到了同样的问题

**Comment by SmallGGgg** [comment]
> > 当我跑hrnet模型的时候，出现了同样的问题，我的路径没有出错啊
> 
> 请问您的这个问题解决了吗？我也遇到了同样的问题

我跑henet的时候也遇到了这个问题，请问你解决了嘛？
