### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/data’

### ISSUE THREAD

**Issue by hsauod** [ifzhang/FairMOT#325]
Firstly, thanks for sharing this great MOT work.

When I trying to run the demo  by ''python track.py mot --load_model ../models/fairmot_dla34.pth --conf_thres 0.6'',

it shows below:

Fix size testing.
training chunk_sizes: [6, 6]
The output will be saved to  /home/ubuntu/workspace/FairMOT-master-2/src/lib/../../exp/mot/default
heads {'hm': 1, 'wh': 4, 'id': 128, 'reg': 2}
Traceback (most recent call last):
  File "track.py", line 271, in <module>
    save_videos=False)
  File "track.py", line 124, in main
    mkdir_if_missing(result_root)
  File "/home/ubuntu/workspace/FairMOT-master-2/src/lib/tracking_utils/utils.py", line 21, in mkdir_if_missing
    os.makedirs(d)
  File "/home/ubuntu/anaconda3/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/ubuntu/anaconda3/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/ubuntu/anaconda3/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 6 more times]
  File "/home/ubuntu/anaconda3/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
**PermissionError: [Errno 13] Permission denied: '/data'**

Do you have any ideas? Thank you in advance.

**Comment by PLester** [comment]
@hsauod you can change the path '/data' to a relative  path like '../results' or an absolute path like "/home/youname/balabala.///"

**Comment by cmtcmt111** [comment]
@hsauod , did you fix it?
I also face the same trouble, could you please tell me how to fix it?
Thank you very much.

**Comment by gau-nernst** [comment]
I faced the same issue and figured it out. The default `--data_dir` is from the author's machine `/data/yfzhang/MOT/JDE`. Just supply the `--data_dir` argument corresponding to your dataset location.
