### ISSUE TITLE
only one class, face tracing

### ISSUE THREAD

**Issue by PALMJJ** [ifzhang/FairMOT#352]
when I trained face tracking, only used one class, face, got this problem

Using tensorboardX
Fix size testing.
training chunk_sizes: [2, 2]
The output will be saved to  /home/hengyuli/FairMOT/src/lib/../../exp/mot/default
Setting up data...
================================================================================
dataset summary
OrderedDict([('widerface', 0)])
total # identities: 1
start index
OrderedDict([('widerface', 0)])
================================================================================
heads {'hm': 1, 'wh': 4, 'id': 128, 'reg': 2}
Namespace(K=500, arch='dla_34', batch_size=4, cat_spec_wh=False, chunk_sizes=[2, 2], conf_thres=0.4, data_cfg='/home/hengyuli/FairMOT/src/lib/cfg/widerface.json', data_dir='/data/yfzhang/MOT/JDE', dataset='jde', debug_dir='/home/hengyuli/FairMOT/src/lib/../../exp/mot/default/debug', dense_wh=False, det_thres=0.3, down_ratio=4, exp_dir='/home/hengyuli/FairMOT/src/lib/../../exp/mot', exp_id='default', fix_res=True, gpus=[0, 1], gpus_str='0, 1', head_conv=256, heads={'hm': 1, 'wh': 4, 'id': 128, 'reg': 2}, hide_data_time=False, hm_weight=1, id_loss='ce', id_weight=1, img_size=(1088, 608), input_h=1088, input_res=1088, input_video='../videos/MOT16-03.mp4', input_w=608, keep_res=False, load_model='', lr=0.0001, lr_step=[50], ltrb=True, master_batch_size=2, mean=None, metric='loss', min_box_area=100, mse_loss=False, nID=1, nms_thres=0.4, norm_wh=False, not_cuda_benchmark=False, not_prefetch_test=False, not_reg_offset=False, num_classes=1, num_epochs=60, num_iters=-1, num_stacks=1, num_workers=8, off_weight=1, output_format='video', output_h=272, output_res=272, output_root='../demos', output_w=152, pad=31, print_iter=0, reg_loss='l1', reg_offset=True, reid_dim=128, resume=False, root_dir='/home/hengyuli/FairMOT/src/lib/../..', save_all=False, save_dir='/home/hengyuli/FairMOT/src/lib/../../exp/mot/default', seed=317, std=None, task='mot', test=False, test_hie=False, test_mot15=False, test_mot16=False, test_mot17=False, test_mot20=False, track_buffer=30, trainval=False, val_hie=False, val_intervals=5, val_mot15=False, val_mot16=False, val_mot17=False, val_mot20=False, vis_thresh=0.5, wh_weight=0.1)
Creating model...
Starting training...
Traceback (most recent call last):
  File "/home/hengyuli/FairMOT/src/train.py", line 98, in <module>
    main(opt)
  File "/home/hengyuli/FairMOT/src/train.py", line 60, in main
    trainer = Trainer(opt, model, optimizer)
  File "/home/hengyuli/FairMOT/src/lib/trains/mot.py", line 78, in __init__
    super(MotTrainer, self).__init__(opt, model, optimizer=optimizer)
  File "/home/hengyuli/FairMOT/src/lib/trains/base_trainer.py", line 28, in __init__
    self.loss_stats, self.loss = self._get_losses(opt)
  File "/home/hengyuli/FairMOT/src/lib/trains/mot.py", line 82, in _get_losses
    loss = MotLoss(opt)
  File "/home/hengyuli/FairMOT/src/lib/trains/mot.py", line 35, in __init__
    self.emb_scale = math.sqrt(2) * math.log(self.nID - 1)
ValueError: math domain error

what's problem, please

**Comment by NeekHua** [comment]
I guess your label dimension isn't same as predicted .Cause loss have error.
