### ISSUE TITLE
同时训练四个类别，进行tracking时报错

### ISSUE THREAD

**Issue by HappyPeanuts** [ifzhang/FairMOT#353]
Traceback (most recent call last):
  File "demo.py", line 44, in <module>
    demo(opt)
  File "demo.py", line 33, in demo
    use_cuda=opt.gpus!=[-1])
  File "FairMOT-master/src/track.py", line 90, in eval_seq
    online_targets = tracker.update(blob, img0)
  File "FairMOT-master/src/lib/tracker/multitracker.py", line 264, in update
    id_feature = id_feature[remain_inds]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 500 but corresponding boolean dimension is 420

**Comment by HappyPeanuts** [comment]
请问这是什么情况呢？期待有人可以提供一点帮助，万分谢谢

**Comment by NeekHua** [comment]
看报错，应该是维度没对上

**Comment by JAYCHOU2020** [comment]
> Traceback (most recent call last):
> File "demo.py", line 44, in
> demo(opt)
> File "demo.py", line 33, in demo
> use_cuda=opt.gpus!=[-1])
> File "FairMOT-master/src/track.py", line 90, in eval_seq
> online_targets = tracker.update(blob, img0)
> File "FairMOT-master/src/lib/tracker/multitracker.py", line 264, in update
> id_feature = id_feature[remain_inds]
> IndexError: boolean index did not match indexed array along dimension 0; dimension is 500 but corresponding boolean dimension is 420

你把代码改成了多类别的了吗？能请教一下如何改的吗？谢谢啦

**Comment by HappyPeanuts** [comment]
非常感谢你能回复，我代码里修改了类别，还是会报错，我看网上说FairMOT只支持单类别的多目标追踪，现在有一个任务需要多类别多目标，我还在研究怎么修改



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月16日(星期三) 下午2:22
收件人: "ifzhang/FairMOT";
抄送: "Author";
主题: Re: [ifzhang/FairMOT] 同时训练四个类别，进行tracking时报错 (#353)





 
看报错，应该是维度没对上
 
&mdash;

**Comment by CaptainEven** [comment]
@HappyPeanuts 请参考我的repo:
https://github.com/CaptainEven/MCMOT

**Comment by HappyPeanuts** [comment]
好的好的，万分感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ifzhang/FairMOT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月1日(星期四) 下午5:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ifzhang/FairMOT] 同时训练四个类别，进行tracking时报错 (#353)





 
@HappyPeanuts 请参考我的repo:
 https://github.com/CaptainEven/MCMOT

**Comment by CaptainEven** [comment]
@HappyPeanuts 觉得有帮助的话，欢迎star和fork

**Comment by HappyPeanuts** [comment]
好的好的，我还有一个疑惑，我在训练FairMOT的时候，我的损失值竟然得到了负值，这是什么情况？是因为本来的损失值设置就存在这种可能吗？




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "ifzhang/FairMOT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月1日(星期四) 下午5:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ifzhang/FairMOT] 同时训练四个类别，进行tracking时报错 (#353)





 
@HappyPeanuts 觉得有帮助的话，欢迎star和fork

**Comment by CaptainEven** [comment]
loss < 0是正常的
