### ISSUE TITLE
Run demo.py

### ISSUE THREAD

**Issue by mtmoreira98** [ifzhang/FairMOT#370]
i run the demo scripts, python demo.py mot --load_model ../models/fairmot_dla34.pth --conf_thres 0.4
Gave me this strange error

Fix size testing.
training chunk_sizes: [6, 6]
The output will be saved to  C:\Users\Miguel Moreira\Desktop\FairMOT\src\lib\..\..\exp\mot\default
heads {'hm': 1, 'wh': 4, 'id': 128, 'reg': 2}
2021-04-16 15:31:21 [INFO]: Starting tracking...
Lenth of the video: 1500 frames
Creating model...
Downloading: "http://dl.yf.io/dla/models\imagenet\dla34-ba72cf86.pth" to C:\Users\Miguel Moreira/.cache\torch\checkpoints\dla34-ba72cf86.pth
Traceback (most recent call last):
  File "demo.py", line 43, in <module>
    demo(opt)
  File "demo.py", line 32, in demo
    use_cuda=opt.gpus!=[-1])
  File "C:\Users\Miguel Moreira\Desktop\FairMOT\src\track.py", line 73, in eval_seq
    tracker = JDETracker(opt, frame_rate=frame_rate)
  File "C:\Users\Miguel Moreira\Desktop\FairMOT\src\lib\tracker\multitracker.py", line 183, in __init__
    self.model = create_model(opt.arch, opt.heads, opt.head_conv)
  File "C:\Users\Miguel Moreira\Desktop\FairMOT\src\lib\models\model.py", line 30, in create_model
    model = get_model(num_layers=num_layers, heads=heads, head_conv=head_conv)
  File "C:\Users\Miguel Moreira\Desktop\FairMOT\src\lib\models\networks\pose_dla_dcn.py", line 491, in get_pose_net
    head_conv=head_conv)
  File "C:\Users\Miguel Moreira\Desktop\FairMOT\src\lib\models\networks\pose_dla_dcn.py", line 434, in __init__
    self.base = globals()[base_name](pretrained=pretrained)
  File "C:\Users\Miguel Moreira\Desktop\FairMOT\src\lib\models\networks\pose_dla_dcn.py", line 314, in dla34
    model.load_pretrained_model(data='imagenet', name='dla34', hash='ba72cf86')
  File "C:\Users\Miguel Moreira\Desktop\FairMOT\src\lib\models\networks\pose_dla_dcn.py", line 300, in load_pretrained_model      
    model_weights = model_zoo.load_url(model_url)
  File "C:\Users\Miguel Moreira\anaconda3\envs\FairMOT\lib\site-packages\torch\hub.py", line 462, in load_state_dict_from_url     
    _download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "C:\Users\Miguel Moreira\anaconda3\envs\FairMOT\lib\site-packages\torch\hub.py", line 372, in _download_url_to_file        
    u = urlopen(url)
  File "C:\Users\Miguel Moreira\anaconda3\envs\FairMOT\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Miguel Moreira\anaconda3\envs\FairMOT\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\Miguel Moreira\anaconda3\envs\FairMOT\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\Miguel Moreira\anaconda3\envs\FairMOT\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\Miguel Moreira\anaconda3\envs\FairMOT\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\Miguel Moreira\anaconda3\envs\FairMOT\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

Any clue?
Thank you

**Comment by Jiaomubaobao233** [comment]
In `src\lib\models\networks\pose_dla_dcn.py`, `get_model_url` uses `os.path.join()` which adds '/' in Linux/macOS but '\\' in Windows.
You may change it into `return 'http://dl.yf.io/dla/models' + '/' + data + '/' + '{}-{}.pth'.format(name, hash)`
