### ISSUE TITLE
using hrnet_18,  found KeyError: 'epoch' 、'state_dict' 

### ISSUE THREAD

**Issue by Maping1026** [ifzhang/FairMOT#389]
![1](https://user-images.githubusercontent.com/70265376/121501469-db740280-ca11-11eb-8a50-62de75e791c7.PNG)
C:\Users\Administrator\anaconda3\envs\pyTorch1.5.1\python.exe E:/Python_Project/Labeling_Aricrafts/code/FairMot_update/FairMOT-master/src/demo.py
2021-06-10 17:23:24 [INFO]: Starting tracking...
Fix size testing.
training chunk_sizes: [2]
The output will be saved to  E:\Python_Project\Labeling_Aricrafts\code\FairMot_update\FairMOT-master\src\lib\..\..\exp\mot\default
heads {'hm': 1, 'wh': 4, 'id': 64, 'reg': 2}
Lenth of the video: 1500 frames
Creating model...
=> loading pretrained model ../models/hrnetv2_w18_imagenet_pretrained.pth
Traceback (most recent call last):
  File "E:/Python_Project/Labeling_Aricrafts/code/FairMot_update/FairMOT-master/src/demo.py", line 43, in <module>
    demo(opt)
  File "E:/Python_Project/Labeling_Aricrafts/code/FairMot_update/FairMOT-master/src/demo.py", line 32, in demo
    use_cuda=opt.gpus!=[-1])
  File "E:\Python_Project\Labeling_Aricrafts\code\FairMot_update\FairMOT-master\src\track.py", line 73, in eval_seq
    tracker = JDETracker(opt, frame_rate=frame_rate)
  File "E:\Python_Project\Labeling_Aricrafts\code\FairMot_update\FairMOT-master\src\lib\tracker\multitracker.py", line 184, in __init__
    self.model = load_model(self.model, opt.load_model)
  File "E:\Python_Project\Labeling_Aricrafts\code\FairMot_update\FairMOT-master\src\lib\models\model.py", line 40, in load_model
    state_dict_ = checkpoint['state_dict']
KeyError: 'state_dict'

**Comment by lila-code** [comment]
@Maping1026 I am facing the same error, did you solve it ?

**Comment by Esha1302** [comment]
@Maping1026 facing the same issue, what was your solution?

**Comment by richardvogg** [comment]
Any solution on this issue yet? I am having the same problem.
