### ISSUE TITLE
KeyError: 'epoch'

### ISSUE THREAD

**Issue by lila-code** [ifzhang/FairMOT#392]
I am trying to test the HRNetV2-W18 model . I used this command :  python demo.py mot --load_model ../models/hrnetv2_w32_imagenet_pretrained.pth --conf_thres 0.4 --arch hrnet_32. And I am getting the message below : 

Fix size testing.
training chunk_sizes: [6, 6]
The output will be saved to FairMOT/src/lib/../../exp/mot/default
heads {'hm': 1, 'wh': 4, 'id': 128, 'reg': 2}
2021-06-11 17:51:57 [INFO]: Starting tracking...
Lenth of the video: 1500 frames
Creating model...
=> loading pretrained model ../models/hrnetv2_w32_imagenet_pretrained.pth
Traceback (most recent call last):
  File "demo.py", line 43, in <module>
    demo(opt)
  File "demo.py", line 30, in demo
    eval_seq(opt, dataloader, 'mot', result_filename,
  File "FairMOT/src/track.py", line 73, in eval_seq
    tracker = JDETracker(opt, frame_rate=frame_rate)
  File "FairMOT/src/lib/tracker/multitracker.py", line 184, in __init__
    self.model = load_model(self.model, opt.load_model)
  File "FairMOT/src/lib/models/model.py", line 39, in load_model
    print('loaded {}, epoch {}'.format(model_path, checkpoint['epoch']))
KeyError: 'epoch'

I got the same error with HRNetV2-W32 model.

**Comment by lila-code** [comment]
At the end I have just used the dla_34 baseline model  instead of the others and it worked
