### ISSUE TITLE
IndexError:

### ISSUE THREAD

**Issue by JAYCHOU2020** [ifzhang/FairMOT#402]
File "C:\Users\zxw\Anaconda3\envs\sort\lib\site-packages\torch\utils\data\dataloader.py", line 846, in _process_data
    data.reraise()
  File "C:\Users\zxw\Anaconda3\envs\sort\lib\site-packages\torch\_utils.py", line 369, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\zxw\Anaconda3\envs\sort\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\zxw\Anaconda3\envs\sort\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\zxw\Anaconda3\envs\sort\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\fairmot\FairMOT-master\src\lib\datasets\dataset\jde.py", line 456, in __getitem__
    wh[k] = 1. * w, 1. * h
IndexError: index 500 is out of bounds for axis 0 with size 500

#################################################
how can i fix this ,please,help,thank u

**Comment by quocnhat** [comment]
hi, have you solved this problem? thanks

**Comment by zengjie617789** [comment]
set a large K
