### ISSUE TITLE
AttributeError: 'LoadImages' object has no attribute 'files'

### ISSUE THREAD

**Issue by devdut1999** [ifzhang/FairMOT#405]
want to try the default settings to run track.py.
python track.py mot --test_mot17 True --load_model ../models/fairmot_dla34.pth --conf_thres 0.4 （I have executed the “python gen_labels_16.py” command on MOT17 data as the code for generating labels is the same） 
Then I got such an error :
Fix size testing.
training chunk_sizes: [6, 6]
The output will be saved to  /content/drive/My Drive/FAIRMOT_ROOT/src/lib/../../exp/mot/default
heads {'hm': 1, 'wh': 4, 'id': 128, 'reg': 2}
2021-06-24 17:21:55 [INFO]: start seq: MOT17-02-SDP
Traceback (most recent call last):
  File "track.py", line 271, in <module>
    save_videos=True)
  File "track.py", line 134, in main
    dataloader = datasets.LoadImages(osp.join(data_root, seq, 'img1'), opt.img_size)
  File "/content/drive/My Drive/FAIRMOT_ROOT/src/lib/datasets/dataset/jde.py", line 32, in __init__
    self.nF = len(self.files)  # number of image files
AttributeError: 'LoadImages' object has no attribute 'files'

I changed the "data_dir" in opts.py. It still doesn't work.  On line 127. self.parser.add_argument('--data_dir', type=str, default='../src/data')
Please help.

**Comment by zengjie617789** [comment]
you should check wether the file exist is under certain dir

**Comment by utkarsh-mishra9** [comment]
@devdut1999 were you able to solve this issue? Do let me know how? I'll be grateful

**Comment by lilingdu** [comment]
@devdut1999 ,solved it or not?

**Comment by HeChengHui** [comment]
Same problem. I believe that could be due to the path being empty.

For me, printing osp.join(data_root, seq, 'img1' gives me .../FairMOT\src\data\MOT17/images/train, which is an empty folder. Hence, I believe that you need to download the MOT17 dataset from JDE [DATA ZOO](https://github.com/Zhongdao/Towards-Realtime-MOT/blob/master/DATASET_ZOO.md) and paste the images into that folder.

I am not sure why does it run on MOT17 instead of the "validation dataset from 2DMOT15" under their Tracking section.

**Comment by xlabd** [comment]
You'll have to set `--val_mot17` as `false` in [opts.py](https://github.com/ifzhang/FairMOT/blob/master/src/lib/opts.py#L107).

Hardcode the value in the script, as passing anything via command line takes it as string, and not boolean.

**Comment by Hemilibeatriz** [comment]
> Você terá que definir `--val_mot17`como `false`em [opts.py](https://github.com/ifzhang/FairMOT/blob/master/src/lib/opts.py#L107) .
> 
> Codifique o valor no script, pois passe qualquer coisa via linha de comando o considere uma string, e não um booleano.

This doesn't seem to work to correct this issue. Do I have to change anything else?
![image](https://github.com/ifzhang/FairMOT/assets/62450495/aa42246b-de39-42d9-be43-f2d86b8d859c)
