### ISSUE TITLE
What does "--ltrb" mean?

### ISSUE THREAD

**Issue by callzhang** [ifzhang/FairMOT#406]
I am trying to train a multi-class model. And I saw the author shared the COCO pretrained model `ctdet_coco_dla_2x`. I think it is a good starting point as the author mentioned that HRNet is not performing as good as DLA backbone. 
When I loaded the pretrained COCO model, the terminal prints:
```
Skip loading parameter hm.2.weight, required shapetorch.Size([10, 256, 1, 1]), loaded shapetorch.Size([80, 256, 1, 1]). If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
Skip loading parameter hm.2.bias, required shapetorch.Size([10]), loaded shapetorch.Size([80]). If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
Skip loading parameter wh.2.weight, required shapetorch.Size([4, 256, 1, 1]), loaded shapetorch.Size([2, 256, 1, 1]). If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
Skip loading parameter wh.2.bias, required shapetorch.Size([4]), loaded shapetorch.Size([2]). If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
```
As to my understanding, the first two lines are OK as I set `num_classes` to 10. However, the other warning seems to be that the pretrained model has different set up than the default arguments. I noticed that there is a `ltrb` argument and I changed it to `False` and it worked without warning. 

What is the effect of change from ltrb to false? What should be considered when changing this value?

**Comment by zengjie617789** [comment]
`ltrb` means left， top， right， bottom； it means the output is the coordinates if you set True, otherwise, it output width and length.

**Comment by zengjie617789** [comment]
`ltrb` means left， top， right， bottom； it means the output is the coordinates if you set True, otherwise, it output width and length.

**Comment by callzhang** [comment]
Does it only related to output? As I have experienced it is also related to model structure (see above). Is it advised to set it to `False` when using ctdet_coco_dla_2x model?

**Comment by helenchiu1221** [comment]
Hi, I faced the same problem.
And the the following is the error message.
Have anyone solved this problem ?

Skip loading parameter hm.2.weight, required shapetorch.Size([1, 256, 1, 1]), loaded shapetorch.Size([80, 256, 1, 1]). If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
Skip loading parameter hm.2.bias, required shapetorch.Size([1]), loaded shapetorch.Size([80]). If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
Skip loading parameter wh.2.weight, required shapetorch.Size([4, 256, 1, 1]), loaded shapetorch.Size([2, 256, 1, 1]). If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
Skip loading parameter wh.2.bias, required shapetorch.Size([4]), loaded shapetorch.Size([2]). If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param id.0.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param id.0.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param id.2.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param id.2.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.

**Comment by KeyuLuo** [comment]
Did you all solve this problem?
I have the same problem！ 

Wenn i train my own dataset，the following problem keeps popping up so that I can't go any further：
--------------------------------------------------------------
Using tensorboardX
Fix size testing.
training chunk_sizes: [3]
The output will be saved to  /content/drive/MyDrive/fairmot/FairMOT/src/lib/../../exp/mot/gazebo_dla34
Setting up data...
================================================================================
dataset summary
OrderedDict([('gazebo', 4205.0)])
total # identities: 4206
start index
OrderedDict([('gazebo', 0)])
================================================================================
heads {'hm': 1, 'wh': 2, 'id': 128, 'reg': 2}
Namespace(K=500, arch='dla_34', batch_size=3, cat_spec_wh=False, chunk_sizes=[3], conf_thres=0.4, data_cfg='../src/lib/cfg/gazebo.json', data_dir='/content/drive/MyDrive/fairmot/gazebo', dataset='jde', debug_dir='/content/drive/MyDrive/fairmot/FairMOT/src/lib/../../exp/mot/gazebo_dla34/debug', dense_wh=False, det_thres=0.3, down_ratio=4, exp_dir='/content/drive/MyDrive/fairmot/FairMOT/src/lib/../../exp/mot', exp_id='gazebo_dla34', fix_res=True, gpus=[0], gpus_str='0', head_conv=256, heads={'hm': 1, 'wh': 2, 'id': 128, 'reg': 2}, hide_data_time=False, hm_weight=1, id_loss='ce', id_weight=1, img_size=(1088, 608), input_h=1280, input_res=1280, input_video='../videos/MOT16-03.mp4', input_w=716, keep_res=False, load_model='../models/fairmot_dla34.pth', lr=0.0001, lr_step=[15], ltrb=False, master_batch_size=3, mean=None, metric='loss', min_box_area=100, mse_loss=False, multi_loss='uncertainty', nID=4206, nms_thres=0.4, norm_wh=False, not_cuda_benchmark=False, not_prefetch_test=False, not_reg_offset=False, num_classes=1, num_epochs=15, num_iters=-1, num_stacks=1, num_workers=8, off_weight=1, output_format='video', output_h=320, output_res=320, output_root='../demos', output_w=179, pad=31, print_iter=0, reg_loss='l1', reg_offset=True, reid_dim=128, resume=False, root_dir='/content/drive/MyDrive/fairmot/FairMOT/src/lib/../..', save_all=False, save_dir='/content/drive/MyDrive/fairmot/FairMOT/src/lib/../../exp/mot/gazebo_dla34', seed=317, std=None, task='mot', test=False, test_hie=False, test_mot15=False, test_mot16=False, test_mot17=False, test_mot20=False, track_buffer=30, trainval=False, val_hie=False, val_intervals=5, val_mot15=False, val_mot16=False, val_mot17=True, val_mot20=False, vis_thresh=0.5, wh_weight=0.1)
Creating model...
Starting training...
loaded ../models/fairmot_dla34.pth, epoch 30
Skip loading parameter wh.2.weight, required shapetorch.Size([2, 256, 1, 1]), loaded shapetorch.Size([4, 256, 1, 1]). If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
Skip loading parameter wh.2.bias, required shapetorch.Size([2]), loaded shapetorch.Size([4]). If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
Traceback (most recent call last):
  File "train.py", line 98, in <module>
    main(opt)
  File "train.py", line 69, in main
    log_dict_train, _ = trainer.train(epoch, train_loader)
  File "/content/drive/MyDrive/fairmot/FairMOT/src/lib/trains/base_trainer.py", line 119, in train
    return self.run_epoch('train', epoch, data_loader)
  File "/content/drive/MyDrive/fairmot/FairMOT/src/lib/trains/base_trainer.py", line 71, in run_epoch
    output, loss, loss_stats = model_with_loss(batch)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/drive/MyDrive/fairmot/FairMOT/src/lib/trains/base_trainer.py", line 19, in forward
    outputs = self.model(batch['input'])
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/drive/MyDrive/fairmot/FairMOT/src/lib/models/networks/pose_dla_dcn.py", line 471, in forward
    x = self.base(x)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/drive/MyDrive/fairmot/FairMOT/src/lib/models/networks/pose_dla_dcn.py", line 290, in forward
    x = getattr(self, 'level{}'.format(i))(x)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/drive/MyDrive/fairmot/FairMOT/src/lib/models/networks/pose_dla_dcn.py", line 214, in forward
    x1 = self.tree1(x, residual)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/drive/MyDrive/fairmot/FairMOT/src/lib/models/networks/pose_dla_dcn.py", line 214, in forward
    x1 = self.tree1(x, residual)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/drive/MyDrive/fairmot/FairMOT/src/lib/models/networks/pose_dla_dcn.py", line 56, in forward
    out += residual
RuntimeError: The size of tensor a (90) must match the size of tensor b (89) at non-singleton dimension 2
------------------------------------------------------------------------
And "ltrb" argument  is set as 'False', but it dosent work!

**Comment by zengjie617789** [comment]
Please edit your format @KeyuLuo

**Comment by KeyuLuo** [comment]
> Please edit your format @KeyuLuo

What's the meaning?  can you explain in detail

**Comment by zengjie617789** [comment]
@KeyuLuo  the font format is hard to read, please edit it.
