### ISSUE TITLE
UserWarning: Error checking compiler version for cl:(dcnv2)

### ISSUE THREAD

**Issue by DioMou** [ifzhang/FairMOT#418]
@ifzhang 
I am having problems with setup the **dcnv2**, it gives me the following warning if I run python setup.py build develop. Although the building process successfully finished, but if I try to **import _ext**, it says `DLL load failed while importing _ext 动态链接库(DLL)初始化例程失败`(dll initlization failed), so I suspect this is because of the user warning below.
`running build`
`running build_ext`
`cl`(it says this is my printed compiler name but I am not running it on visual studio, this is simply vscode with python 3.8 torch 3.7.0)
`Traceback (most recent call last):`(self printed traceback, start here)
 ` File "C:\Users\LXAB\anaconda3\envs\mltorch\lib\site-packages\torch\utils\cpp_extension.py", line 270, in check_compiler_abi_compatibility
    compiler_info = subprocess.check_output(compiler, stderr=subprocess.STDOUT)`
 ` File "C:\Users\LXAB\anaconda3\envs\mltorch\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,`
  `File "C:\Users\LXAB\anaconda3\envs\mltorch\lib\subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:`
  `File "C:\Users\LXAB\anaconda3\envs\mltorch\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,`
  `File "C:\Users\LXAB\anaconda3\envs\mltorch\lib\subprocess.py", line 1311, in _execute_child     
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,`
`FileNotFoundError: [WinError 2] 系统找不到指定的文件。`(means system cannot find file,ends here)
`C:\Users\LXAB\anaconda3\envs\mltorch\lib\site-packages\torch\utils\cpp_extension.py:278: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building '_ext' extension`
I did try to change decode to gbk but does not work. Anybody can help?

**Comment by DEEPMINDing** [comment]
请问你解决这个问题了吗，我也遇到了同样的问题

**Comment by DioMou** [comment]
> 
> 
> 请问你解决这个问题了吗，我也遇到了同样的问题

没有，我认为有可能是系统的问题，dcn可能得在linux上才能弄，windows我认为可能有一些谦容问题。The original dcnv2 module specified that it is developed under linux environment. WS2可能能够解决，但需要重新安装cuda等一系列操作，我没有完全尝试。要重新train的话我试了下应该只有hrnet可以直接用
