### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by muhabdulhaq** [ifzhang/FairMOT#431]
I got this error when change the paths in src/gen_labels_crowd_id.py

```
(FairMOT) root@8ea6c8f38f0f:~/FairMOT/src# python gen_labels_crowd_id.py
fpath /root/FairMOT/crowdhuman/annotation_train.odgt
0
Traceback (most recent call last):
  File "gen_labels_crowd_id.py", line 58, in <module>
    gen_labels_crowd(data_train, label_train, ann_train)
  File "gen_labels_crowd_id.py", line 36, in gen_labels_crowd
    img_height, img_width = img.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'
(FairMOT) root@8ea6c8f38f0f:~/FairMOT/src# python gen_labels_crowd_det.py
fpath /root/FairMOT/crowdhuman/annotation_train.odgt
0
Traceback (most recent call last):
  File "gen_labels_crowd_det.py", line 60, in <module>
    gen_labels_crowd(data_train, label_train, ann_train)
  File "gen_labels_crowd_det.py", line 36, in gen_labels_crowd
    img_height, img_width = img.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by spyisong** [comment]
Same problem, how do you solve it?

**Comment by sieumap43** [comment]
To anyone who is having the problem, the original directory structure from the crowdhuman website is different from the one they are using here. You need to copy the train and val directories and rename them from Images to train and val respectively. (My instruction is not very clear but you get the gist)
