### ISSUE TITLE
model maybe corrupted when I run training or demo.

### ISSUE THREAD

**Issue by rabbitegg** [ifzhang/FairMOT#48]
Hello, I downloaded your models as your point. But when I train or run demo they show as follow:
`RuntimeError: unexpected EOF, expected 1132938 more bytes. The file might be corrupted.
`
I tried the solution searched on Google, but not solved. 

How to solve it? Thank you.

The training terminal output as follow:
`Using tensorboardX
Fix size testing.
training chunk_sizes: [2]
The output will be saved to  /media/lalalademaxiya/FairMOT/src/lib/../../exp/mot/all_dla34
Setting up data...
================================================================================
dataset summary
OrderedDict([('mot15', 501.0)])
total # identities: 502
start index
OrderedDict([('mot15', 0)])
================================================================================
heads {'hm': 1, 'wh': 2, 'id': 512, 'reg': 2}
Namespace(K=128, arch='dla_34', batch_size=2, cat_spec_wh=False, chunk_sizes=[2], conf_thres=0.6, data_cfg='../src/lib/cfg/mot15.json', data_dir='/media/lalalademaxiya/FairMOT/MOTdatasets/dataset', dataset='jde', debug_dir='/media/lalalademaxiya/FairMOT/src/lib/../../exp/mot/all_dla34/debug', dense_wh=False, det_thres=0.3, down_ratio=4, exp_dir='/media/lalalademaxiya/FairMOT/src/lib/../../exp/mot', exp_id='all_dla34', fix_res=True, gpus=[0], gpus_str='0', head_conv=256, heads={'hm': 1, 'wh': 2, 'id': 512, 'reg': 2}, hide_data_time=False, hm_weight=1, id_loss='ce', id_weight=1, img_size=(1088, 608), input_h=1088, input_res=1088, input_video='../videos/MOT16-03.mp4', input_w=608, keep_res=False, load_model='../models/ctdet_coco_dla_2x.pth', lr=0.0001, lr_step=[20, 27], master_batch_size=2, mean=None, metric='loss', min_box_area=200, mse_loss=False, nID=502, nms_thres=0.4, norm_wh=False, not_cuda_benchmark=False, not_prefetch_test=False, not_reg_offset=False, num_classes=1, num_epochs=30, num_iters=-1, num_stacks=1, num_workers=8, off_weight=1, output_format='video', output_h=272, output_res=272, output_root='../results', output_w=152, pad=31, print_iter=0, reg_loss='l1', reg_offset=True, reid_dim=512, resume=False, root_dir='/media/lalalademaxiya/FairMOT/src/lib/../..', save_all=False, save_dir='/media/lalalademaxiya/FairMOT/src/lib/../../exp/mot/all_dla34', seed=317, std=None, task='mot', test=False, test_mot15=False, test_mot16=False, test_mot17=False, test_mot20=False, track_buffer=30, trainval=False, val_intervals=5, val_mot15=False, val_mot16=False, val_mot17=False, val_mot20=False, vis_thresh=0.5, wh_weight=0.1)
cp: target 'copy/FairMOT/src/lib/../../exp/mot/all_dla34/logs_2020-04-19-18-36/' is not a directory
Creating model...
Traceback (most recent call last):
  File "train.py", line 97, in <module>
    main(opt)
  File "train.py", line 43, in main
    model = create_model(opt.arch, opt.heads, opt.head_conv)
  File "/media/lalalademaxiya/FairMOT/src/lib/models/model.py", line 25, in create_model
    model = get_model(num_layers=num_layers, heads=heads, head_conv=head_conv)
  File "/media/lalalademaxiya/FairMOT/src/lib/models/networks/pose_dla_dcn.py", line 490, in get_pose_net
    head_conv=head_conv)
  File "/media/lalalademaxiya/FairMOT/src/lib/models/networks/pose_dla_dcn.py", line 433, in __init__
    self.base = globals()[base_name](pretrained=pretrained)
  File "/media/lalalademaxiya/FairMOT/src/lib/models/networks/pose_dla_dcn.py", line 313, in dla34
    model.load_pretrained_model(data='imagenet', name='dla34', hash='ba72cf86')
  File "/media/lalalademaxiya/FairMOT/src/lib/models/networks/pose_dla_dcn.py", line 299, in load_pretrained_model
    model_weights = model_zoo.load_url(model_url)
  File "/home/XXX/.local/lib/python3.6/site-packages/torch/hub.py", line 506, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/home/XXX/.local/lib/python3.6/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/XXX/.local/lib/python3.6/site-packages/torch/serialization.py", line 709, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 1132938 more bytes. The file might be corrupted.
terminate called after throwing an instance of 'c10::Error'
  what():  owning_ptr == NullType::singleton() || owning_ptr->refcount_.load() > 0 INTERNAL ASSERT FAILED at /pytorch/c10/util/intrusive_ptr.h:348, please report a bug to PyTorch. intrusive_ptr: Can only intrusive_ptr::reclaim() owning pointers that were created using intrusive_ptr::release(). (reclaim at /pytorch/c10/util/intrusive_ptr.h:348)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7fd0e4588193 in /home/XXX/.local/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x18cd59f (0x7fd08083259f in /home/XXX/.local/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #2: THStorage_free + 0x17 (0x7fd080ffaba7 in /home/XXX/.local/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x55d65d (0x7fd0e784965d in /home/XXX/.local/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #4: python3() [0x54f6e6]
frame #5: python3() [0x5734e0]
frame #6: python3() [0x4b1a28]
frame #7: python3() [0x589078]
frame #8: python3() [0x5ade68]
frame #9: python3() [0x5ade7e]
frame #10: python3() [0x5ade7e]
frame #11: python3() [0x5ade7e]
frame #12: python3() [0x5ade7e]
frame #13: python3() [0x5ade7e]
frame #14: python3() [0x5ade7e]
frame #15: python3() [0x5ade7e]
frame #16: python3() [0x5ade7e]
frame #17: python3() [0x5ade7e]
frame #18: python3() [0x56be56]
<omitting python frames>
frame #24: __libc_start_main + 0xe7 (0x7fd0ecc45b97 in /lib/x86_64-linux-gnu/libc.so.6)

Aborted (core dumped)
`

**Comment by ifzhang** [comment]
You may try downloading the model again, either from Google or Baidu.

**Comment by rabbitegg** [comment]
> You may try downloading the model again, either from Google or Baidu.

Will the file size be different on Ubuntu and Windows? I copy the file to Ubuntu and the file size will change.
Is this the cause of the problem?

**Comment by wuchao1235-i** [comment]
> > You may try downloading the model again, either from Google or Baidu.
> 
> Will the file size be different on Ubuntu and Windows? I copy the file to Ubuntu and the file size will change.
> Is this the cause of the problem?

Hello, have you solved your problem? My situation is the same as yours.

**Comment by rabbitegg** [comment]
> > > You may try downloading the model again, either from Google or Baidu.
> > 
> > 
> > Will the file size be different on Ubuntu and Windows? I copy the file to Ubuntu and the file size will change.
> > Is this the cause of the problem?
> 
> Hello, have you solved your problem? My situation is the same as yours.

I didn't solve this problem.
I gave up using the existing model, and tried to train by myself. Then I could continue the next step.

**Comment by eeric** [comment]
download again
wget http://dl.yf.io/dla/models/imagenet/dla34-ba72cf86.pth
