### ISSUE TITLE
Error of pretraining CrowdHuman dataset

### ISSUE THREAD

**Issue by nornen0202** [ifzhang/FairMOT#484]
How can I solve the below problem?

########## Train Log ###############
mot/crowdhuman_dla34| train: [1][4240/19370]|Tot: 0:28:23 |ETA: 0:00:00 |loss 20.8643 |hm_loss 1.6064 |wh_loss 4.8034 |off_loss 0.2379 |id_loss 13.2775 |Data 0.020s(0.020s) |Net 0.402s
mot/crowdhuman_dla34| train: [1][4250/19370]|Tot: 0:28:27 |ETA: 0:00:00 |loss 20.8518 |hm_loss 1.6054 |wh_loss 4.7970 |off_loss 0.2379 |id_loss 13.2775 |Data 0.020s(0.020s) |Net 0.402s
mot/crowdhuman_dla34| train: [1][4260/19370]|Tot: 0:28:31 |ETA: 0:00:00 |loss 20.8440 |hm_loss 1.6060 |wh_loss 4.7946 |off_loss 0.2380 |id_loss 13.2775 |Data 0.020s(0.020s) |Net 0.402s
mot/crowdhuman_dla34| train: [1][4270/19370]|Tot: 0:28:35 |ETA: 0:00:00 |loss 20.8332 |hm_loss 1.6056 |wh_loss 4.7901 |off_loss 0.2380 |id_loss 13.2776 |Data 0.020s(0.020s) |Net 0.402s
Traceback (most recent call last):
  File "train.py", line 98, in <module>
    main(opt)
  File "train.py", line 69, in main
    log_dict_train, _ = trainer.train(epoch, train_loader)
  File "/disk2/FairMOT/src/lib/trains/base_trainer.py", line 120, in train
    return self.run_epoch('train', epoch, data_loader)
  File "/disk2/FairMOT/src/lib/trains/base_trainer.py", line 85, in run_epoch
    loss_stats[l].mean().item(), batch['input'].size(0))
AttributeError: 'int' object has no attribute 'mean'
#####################################################

Actually, before applying the below solution (https://github.com/ifzhang/FairMOT/issues/205#issuecomment-671796453), there was the 'nan' loss problem, i.e., all losses are changed to 'nan' after a few iterations.

#### line 78 in 'mot.py' ####
if len(id_target) > 0 and len(id_output) > 0:
    id_loss += self.IDLoss(id_output, id_target)
######################

**Comment by biibabu** [comment]
Hello, I had the same problem, how did you solve it?

**Comment by Gwofoo** [comment]
I met this "is_loss nan" problem too. I use my custum datasets to train, the origin train images contain some backgroud without any objects. Then I removed these backgroud images. But this problem still occured. Then I set `augment=False` in `train.py`, the problem dispeared. So I infer that the objects may be clipped or something else with augment operation, that leads to no objects in the images. Because there are only one or two objects in my datasets.
