### ISSUE TITLE
RuntimeError: No CUDA GPUs are available

### ISSUE THREAD

**Issue by leminhhuy132** [ifzhang/FairMOT#515]
I got this error when i run follow command:
```
python track.py mot --load_model ../models/fairmot_dla34.pth --conf_thres 0.6 --test_mot16 True
```
Error:
```
Fix size testing.
training chunk_sizes: [12]
The output will be saved to  /home/minhhuy/Desktop/Python/FairMOT/src/lib/../../exp/mot/default
heads {'hm': 1, 'wh': 4, 'id': 128, 'reg': 2}
2022-07-04 10:33:39 [INFO]: start seq: MOT16-01
2022-07-04 10:33:39 [INFO]: start seq: MOT16-01
/home/minhhuy/Desktop/Python/FairMOT/Data/MOT16/test/MOT16-01/img1
Creating model...
loaded ../models/fairmot_dla34.pth, epoch 30
Traceback (most recent call last):
  File "track.py", line 271, in <module>
    save_videos=False)
  File "track.py", line 139, in main
    save_dir=output_dir, show_image=show_image, frame_rate=frame_rate)
  File "track.py", line 73, in eval_seq
    tracker = JDETracker(opt, frame_rate=frame_rate)
  File "/home/minhhuy/Desktop/Python/FairMOT/src/lib/tracker/multitracker.py", line 181, in __init__
    self.model = self.model.to(opt.device)
  File "/home/minhhuy/anaconda3/envs/smartclass/lib/python3.7/site-packages/torch/nn/modules/module.py", line 907, in to
    return self._apply(convert)
  File "/home/minhhuy/anaconda3/envs/smartclass/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/home/minhhuy/anaconda3/envs/smartclass/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/home/minhhuy/anaconda3/envs/smartclass/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/home/minhhuy/anaconda3/envs/smartclass/lib/python3.7/site-packages/torch/nn/modules/module.py", line 601, in _apply
    param_applied = fn(param)
  File "/home/minhhuy/anaconda3/envs/smartclass/lib/python3.7/site-packages/torch/nn/modules/module.py", line 905, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/minhhuy/anaconda3/envs/smartclass/lib/python3.7/site-packages/torch/cuda/__init__.py", line 216, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
```
But when i try run ```print(torch.cuda.is_available())``` in another file it return ```True```

**Comment by leminhhuy132** [comment]
I fixed this error by comment ```os.environ['CUDA_VISIBLE_DEVICES'] = '1'```
