### ISSUE TITLE
AttributeError: 'LoadImages' object has no attribute 'files'

### ISSUE THREAD

**Issue by Melikamuliyih** [ifzhang/FairMOT#522]
cmd : python track.py mot --test_mot17 True --load_model ../models/fairmot_dla34.pth --conf_thres 0.4

Fix size testing.
training chunk_sizes: [6, 6]
The output will be saved to  /root/userfolder/FairMOT/src/lib/../../exp/mot/default
heads {'hm': 1, 'wh': 4, 'id': 128, 'reg': 2}
2022-09-29 19:06:34 [INFO]: start seq: MOT17-02-SDP
Traceback (most recent call last):
  File "track.py", line 265, in <module>
    main(opt,
  File "track.py", line 134, in main
    dataloader = datasets.LoadImages(osp.join(data_root, seq, 'img1'), opt.img_size)
  File "/root/userfolder/FairMOT/src/lib/datasets/dataset/jde.py", line 32, in __init__
    self.nF = len(self.files)  # number of image files
AttributeError: 'LoadImages' object has no attribute 'files'

**Comment by Melikamuliyih** [comment]
Solved

**Comment by Rhfofngm** [comment]
how to solve?
