### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by felipearrudamoura** [ifzhang/FairMOT#523]
Hi, guys. Anyone can help me? I have already tried to re-install both cuda and pytorch, with no success. 
Thanks!

-----------------------------------------------

sh experiments/crowdhuman_dla34.sh
Using tensorboardX
Fix size testing.
training chunk_sizes: [4, 4]
The output will be saved to  /media/preto/HD6TB/FairMOT/src/lib/../../exp/mot/crowdhuman_dla34
Setting up data...
================================================================================
dataset summary
OrderedDict([('CrowdHuman_train01', 339565.0), ('CrowedHuman_test', 99481.0)])
total # identities: 439047
start index
OrderedDict([('CrowdHuman_train01', 0), ('CrowedHuman_test', 339565.0)])
================================================================================
heads {'hm': 1, 'wh': 4, 'id': 128, 'reg': 2}
Namespace(K=500, arch='dla_34', batch_size=8, cat_spec_wh=False, chunk_sizes=[4, 4], conf_thres=0.4, data_cfg='../src/lib/cfg/crowdhuman.json', data_dir='/home/zyf/dataset', dataset='jde', debug_dir='/media/preto/HD6TB/FairMOT/src/lib/../../exp/mot/crowdhuman_dla34/debug', dense_wh=False, det_thres=0.3, down_ratio=4, exp_dir='/media/preto/HD6TB/FairMOT/src/lib/../../exp/mot', exp_id='crowdhuman_dla34', fix_res=True, gpus=[0, 1], gpus_str='0,1', head_conv=256, heads={'hm': 1, 'wh': 4, 'id': 128, 'reg': 2}, hide_data_time=False, hm_weight=1, id_loss='ce', id_weight=1, img_size=(1088, 608), input_h=1088, input_res=1088, input_video='../videos/MOT16-03.mp4', input_w=608, keep_res=False, load_model='../models/ctdet_coco_dla_2x.pth', lr=0.0001, lr_step=[50], ltrb=True, master_batch_size=4, mean=None, metric='loss', min_box_area=100, mse_loss=False, multi_loss='uncertainty', nID=439047, nms_thres=0.4, norm_wh=False, not_cuda_benchmark=False, not_prefetch_test=False, not_reg_offset=False, num_classes=1, num_epochs=60, num_iters=-1, num_stacks=1, num_workers=8, off_weight=1, output_format='video', output_h=272, output_res=272, output_root='../demos', output_w=152, pad=31, print_iter=0, reg_loss='l1', reg_offset=True, reid_dim=128, resume=False, root_dir='/media/preto/HD6TB/FairMOT/src/lib/../..', save_all=False, save_dir='/media/preto/HD6TB/FairMOT/src/lib/../../exp/mot/crowdhuman_dla34', seed=317, std=None, task='mot', test=False, test_hie=False, test_mot15=False, test_mot16=False, test_mot17=False, test_mot20=False, track_buffer=30, trainval=False, val_hie=False, val_intervals=5, val_mot15=False, val_mot16=False, val_mot17=True, val_mot20=False, vis_thresh=0.5, wh_weight=0.1)
Creating model...
Starting training...
Traceback (most recent call last):
  File "train.py", line 98, in <module>
    main(opt)
  File "train.py", line 61, in main
    trainer.set_device(opt.gpus, opt.chunk_sizes, opt.device)
  File "/media/preto/HD6TB/FairMOT/src/lib/trains/base_trainer.py", line 34, in set_device
    self.model_with_loss = DataParallel(
  File "/home/preto/anaconda3/envs/FairMOT/lib/python3.8/site-packages/torch/nn/modules/module.py", line 927, in to
    return self._apply(convert)
  File "/home/preto/anaconda3/envs/FairMOT/lib/python3.8/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/home/preto/anaconda3/envs/FairMOT/lib/python3.8/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/home/preto/anaconda3/envs/FairMOT/lib/python3.8/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/home/preto/anaconda3/envs/FairMOT/lib/python3.8/site-packages/torch/nn/modules/module.py", line 602, in _apply
    param_applied = fn(param)
  File "/home/preto/anaconda3/envs/FairMOT/lib/python3.8/site-packages/torch/nn/modules/module.py", line 925, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/preto/anaconda3/envs/FairMOT/lib/python3.8/site-packages/torch/cuda/__init__.py", line 211, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by sompt22** [comment]
install cudatoolkit-dev package and recompile DCNv2
