### ISSUE TITLE
RuntimeError: read(): fd 3 failed with Permission denied

### ISSUE THREAD

**Issue by karslishuai** [ifzhang/FairMOT#537]
(FairMOTm) C:\Users\Administrator\clone\FairMOT\src>python demo.py mot --load_model ../models/fairmot_dla34.pth --conf_thres 0.4
Fix size testing.
training chunk_sizes: [6, 6]
The output will be saved to  C:\Users\Administrator\clone\FairMOT\src\lib\..\..\exp\mot\default
heads {'hm': 1, 'wh': 4, 'id': 128, 'reg': 2}
2023-03-19 16:32:56 [INFO]: Starting tracking...
Lenth of the video: 1500 frames
Creating model...
Traceback (most recent call last):
  File "demo.py", line 43, in <module>
    demo(opt)
  File "demo.py", line 30, in demo
    eval_seq(opt, dataloader, 'mot', result_filename,
  File "C:\Users\Administrator\clone\FairMOT\src\track.py", line 73, in eval_seq
    tracker = JDETracker(opt, frame_rate=frame_rate)
  File "C:\Users\Administrator\clone\FairMOT\src\lib\tracker\multitracker.py", line 179, in __init__
    self.model = create_model(opt.arch, opt.heads, opt.head_conv)
  File "C:\Users\Administrator\clone\FairMOT\src\lib\models\model.py", line 32, in create_model
    model = get_model(num_layers=num_layers, heads=heads, head_conv=head_conv)
  File "C:\Users\Administrator\clone\FairMOT\src\lib\models\networks\pose_dla_dcn.py", line 486, in get_pose_net
    model = DLASeg('dla{}'.format(num_layers), heads,
  File "C:\Users\Administrator\clone\FairMOT\src\lib\models\networks\pose_dla_dcn.py", line 434, in __init__
    self.base = globals()[base_name](pretrained=pretrained)
  File "C:\Users\Administrator\clone\FairMOT\src\lib\models\networks\pose_dla_dcn.py", line 314, in dla34
    model.load_pretrained_model(data='imagenet', name='dla34', hash='ba72cf86')
  File "C:\Users\Administrator\clone\FairMOT\src\lib\models\networks\pose_dla_dcn.py", line 300, in load_pretrained_model
    model_weights = model_zoo.load_url(model_url)
  File "D:\ANACONDA\envs\FairMOTm\lib\site-packages\torch\hub.py", line 559, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "D:\ANACONDA\envs\FairMOTm\lib\site-packages\torch\serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\ANACONDA\envs\FairMOTm\lib\site-packages\torch\serialization.py", line 781, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: read(): fd 3 failed with Permission denied

i wonder how to fix it

**Comment by G1sao** [comment]
Hey, I'm also having the same issue right now, did you fix it?
