### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by CaptainEven** [ifzhang/FairMOT#64]
running build
running build_ext
building '_ext' extension
Emitting ninja build file /mnt/diskb/even/FairMOT/src/lib/models/networks/DCNv2/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] /usr/local/cuda/bin/nvcc -DWITH_CUDA -I/mnt/diskb/even/FairMOT/src/lib/models/networks/DCNv2/src -I/home/jaya/.local/lib/python3.7/site-packages/torch/include -I/home/jaya/.local/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/jaya/.local/lib/python3.7/site-packages/torch/include/TH -I/home/jaya/.local/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/jaya/.conda/envs/FairMOT/include/python3.7m -c -c /mnt/diskb/even/FairMOT/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_cuda.cu -o /mnt/diskb/even/FairMOT/src/lib/models/networks/DCNv2/build/temp.linux-x86_64-3.7/mnt/diskb/even/FairMOT/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_52,code=sm_52 -std=c++14
FAILED: /mnt/diskb/even/FairMOT/src/lib/models/networks/DCNv2/build/temp.linux-x86_64-3.7/mnt/diskb/even/FairMOT/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_cuda.o 
/usr/local/cuda/bin/nvcc -DWITH_CUDA -I/mnt/diskb/even/FairMOT/src/lib/models/networks/DCNv2/src -I/home/jaya/.local/lib/python3.7/site-packages/torch/include -I/home/jaya/.local/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/jaya/.local/lib/python3.7/site-packages/torch/include/TH -I/home/jaya/.local/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/jaya/.conda/envs/FairMOT/include/python3.7m -c -c /mnt/diskb/even/FairMOT/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_cuda.cu -o /mnt/diskb/even/FairMOT/src/lib/models/networks/DCNv2/build/temp.linux-x86_64-3.7/mnt/diskb/even/FairMOT/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_52,code=sm_52 -std=c++14
/mnt/diskb/even/FairMOT/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_cuda.cu(86): error: identifier "THCState_getCurrentStream" is undefined

/mnt/diskb/even/FairMOT/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_cuda.cu(182): error: identifier "THCState_getCurrentStream" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_00005e88_00000000-6_dcn_v2_cuda.cpp1.ii".
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/jaya/.local/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1400, in _run_ninja_build
    check=True)
  File "/home/jaya/.conda/envs/FairMOT/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 65, in <module>
    cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
  File "/home/jaya/.local/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/home/jaya/.conda/envs/FairMOT/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/jaya/.conda/envs/FairMOT/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/jaya/.conda/envs/FairMOT/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/jaya/.conda/envs/FairMOT/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/jaya/.conda/envs/FairMOT/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/jaya/.conda/envs/FairMOT/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/jaya/.local/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/home/jaya/.local/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/jaya/.conda/envs/FairMOT/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/jaya/.local/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 580, in build_extensions
    build_ext.build_extensions(self)
  File "/home/jaya/.local/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/jaya/.conda/envs/FairMOT/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/jaya/.conda/envs/FairMOT/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/jaya/.local/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/jaya/.conda/envs/FairMOT/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/jaya/.local/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 423, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/jaya/.local/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/jaya/.local/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1413, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

**Comment by blackCmd** [comment]
Me too. "ninja: build stopped: subcommand failed."

**Comment by ZiyanZhu1994** [comment]
Same here. Anyone has fixed this issue?

**Comment by blackCmd** [comment]
> Same here. Anyone has fixed this issue?

I've fixed. 
Try to change your Pytorch version to 1.4 or 1.5 etc..
