### ISSUE TITLE
[Fine-tune only Detector component]

### ISSUE THREAD

**Issue by vuthede** [ifzhang/FairMOT#70]
I wonder that is there any way to fine-tune the model on only detector component?
I ask that because I have the custom dataset but the label have just x,y,w,h, and class_id. it dont have the identity_id. So I think we can  train the model only on detector component by freezing the Reid component and hopefully it can improve the detector part in our dataset but may be it will reduce performance of Reid.
What do u guys think about that? Thank you.

**Comment by ifzhang** [comment]
In fact, our training dataset includes dataset that do not have id labels, like cityperson. You can follow the way we train cityperson: the id labels are set to -1 and the cross entropy loss of the reid branch will ignore -1. So you can just train the detection part.

**Comment by vuthede** [comment]
>The id labels are set to -1 and the cross entropy loss of the reid branch will ignore -1. So you can just train the detection part.
@ifzhang   Oh very nice! Interesting. Thank you for quick answer.

**Comment by StianHanssen** [comment]
@ifzhang When I follow what you say I get:
```
Starting training...
Traceback (most recent call last):
  File "train.py", line 97, in <module>
    main(opt)
  File "train.py", line 63, in main
    trainer = Trainer(opt, model, optimizer)
  File "/home/stian/FairMOT/src/lib/trains/mot.py", line 88, in __init__
    super(MotTrainer, self).__init__(opt, model, optimizer=optimizer)
  File "/home/stian/FairMOT/src/lib/trains/base_trainer.py", line 28, in __init__
    self.loss_stats, self.loss = self._get_losses(opt)
  File "/home/stian/FairMOT/src/lib/trains/mot.py", line 92, in _get_losses
    loss = MotLoss(opt)
  File "/home/stian/FairMOT/src/lib/trains/mot.py", line 34, in __init__
    self.emb_scale = math.sqrt(2) * math.log(self.nID - 1)
ValueError: math domain error
```
As there are no tracking IDs in the train dataset, you get a `max_index` of -1, which leads to `self.tid_num[ds]` to have one entry with value 0, so then `self.nID = int(last_index + 1)` is one. Then on line 34 in mot.py, you therefore get a log calculation for 0.

Can I work around this or do I need an additional dataset with tracking IDs to avoid this issue?

**Comment by boy-new-2019** [comment]
> @ifzhang当我按照您说的去做时，我会得到：
> 
> ```
> Starting training...
> Traceback (most recent call last):
>   File "train.py", line 97, in <module>
>     main(opt)
>   File "train.py", line 63, in main
>     trainer = Trainer(opt, model, optimizer)
>   File "/home/stian/FairMOT/src/lib/trains/mot.py", line 88, in __init__
>     super(MotTrainer, self).__init__(opt, model, optimizer=optimizer)
>   File "/home/stian/FairMOT/src/lib/trains/base_trainer.py", line 28, in __init__
>     self.loss_stats, self.loss = self._get_losses(opt)
>   File "/home/stian/FairMOT/src/lib/trains/mot.py", line 92, in _get_losses
>     loss = MotLoss(opt)
>   File "/home/stian/FairMOT/src/lib/trains/mot.py", line 34, in __init__
>     self.emb_scale = math.sqrt(2) * math.log(self.nID - 1)
> ValueError: math domain error
> ```
> 
> 由于火车数据集中没有跟踪ID，您将获得`max_index`-1，这将导致`self.tid_num[ds]`其中一个条目的值为0，因此`self.nID = int(last_index + 1)`值为1。然后在mot.py的第34行上，您将获得对数的日志计算0。
> 
> 我可以解决此问题，还是需要其他具有跟踪ID的数据集来避免此问题？

How do you solve this problem? I commented it out, but I ran into new problems
mot/ft_mot20_dla34_pppTraceback (most recent call last):
  File "train.py", line 106, in <module>
    main(opt)
  File "train.py", line 68, in main
    log_dict_train, _ = trainer.train(epoch, train_loader)
  File "/media/goo/use2download/FairMOT/src/lib/trains/base_trainer.py", line 119, in train
    return self.run_epoch('train', epoch, data_loader)
  File "/media/goo/use2download/FairMOT/src/lib/trains/base_trainer.py", line 71, in run_epoch
    output, loss, loss_stats = model_with_loss(batch)
  File "/home/goo/anaconda3/envs/fairmot/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/goo/use2download/FairMOT/src/lib/trains/base_trainer.py", line 19, in forward
    outputs = self.model(batch['input'])
  File "/home/goo/anaconda3/envs/fairmot/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/goo/use2download/FairMOT/src/lib/models/networks/pose_dla_dcn.py", line 467, in forward
    x = self.base(x)
  File "/home/goo/anaconda3/envs/fairmot/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/goo/use2download/FairMOT/src/lib/models/networks/pose_dla_dcn.py", line 283, in forward
    x = getattr(self, 'level{}'.format(i))(x)
  File "/home/goo/anaconda3/envs/fairmot/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/goo/use2download/FairMOT/src/lib/models/networks/pose_dla_dcn.py", line 213, in forward
    x1 = self.tree1(x, residual)
  File "/home/goo/anaconda3/envs/fairmot/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/goo/use2download/FairMOT/src/lib/models/networks/pose_dla_dcn.py", line 213, in forward
    x1 = self.tree1(x, residual)
  File "/home/goo/anaconda3/envs/fairmot/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/goo/use2download/FairMOT/src/lib/models/networks/pose_dla_dcn.py", line 55, in forward
    out += residual
RuntimeError: The size of tensor a (68) must match the size of tensor b (67) at non-singleton dimension 3

**Comment by faruknane** [comment]
@StianHanssen I tried to train a model using only Citypersons dataset. It doesn't have identities. All identities are -1. I got self.nID = 1 and it throws an error at that row. Did you find any solutions to this?

My second question is that does this line throw error for a dataset which has identities.
