### ISSUE TITLE
ModuleNotFoundError: No module named '_ext

### ISSUE THREAD

**Issue by Analystharsh** [ifzhang/FairMOT#83]
Found this error while running demo.py file

`/content/drive/My Drive/FairMOT/src
Traceback (most recent call last):
  File "demo.py", line 14, in <module>
    from track import eval_seq
  File "/content/drive/My Drive/FairMOT/src/track.py", line 15, in <module>
    from tracker.multitracker import JDETracker
  File "/content/drive/My Drive/FairMOT/src/lib/tracker/multitracker.py", line 8, in <module>
    from models.model import create_model, load_model
  File "/content/drive/My Drive/FairMOT/src/lib/models/model.py", line 8, in <module>
    from .networks.pose_dla_dcn import get_pose_net as get_dla_dcn
  File "/content/drive/My Drive/FairMOT/src/lib/models/networks/pose_dla_dcn.py", line 15, in <module>
    from .DCNv2.dcn_v2 import DCN
  File "/content/drive/My Drive/FairMOT/src/lib/models/networks/DCNv2/dcn_v2.py", line 13, in <module>
    import _ext as _backend
ModuleNotFoundError: No module named '_ext'`

**Comment by zihan987** [comment]
You should install DCNv2

**Comment by Thunzhsh** [comment]
> You should install DCNv2

install DCNv2是run setup.py吗，但是我run时遇到问题
/usr/local/cuda/bin/nvcc -DWITH_CUDA -I/content/drive/My Drive/Colab Notebooks/FairMOT-master/src/lib/models/networks/DCNv2/src -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c /content/drive/My Drive/Colab Notebooks/FairMOT-master/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_cuda.cu -o build/temp.linux-x86_64-3.6/content/drive/My Drive/Colab Notebooks/FairMOT-master/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -std=c++14
/content/drive/My Drive/Colab Notebooks/FairMOT-master/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_cuda.cu(86): error: identifier "THCState_getCurrentStream" is undefined

/content/drive/My Drive/Colab Notebooks/FairMOT-master/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_cuda.cu(182): error: identifier "THCState_getCurrentStream" is undefined
请问该如何解决

**Comment by JadeYuan** [comment]
how to install DCNv2 ?

**Comment by mainguyenanhvu** [comment]
Please give me the way to install DCNv2 on Google Colab. Thank you very much.

**Comment by Thunzhsh** [comment]
> Please give me the way to install DCNv2 on Google Colab. Thank you very much.

through bash
you can open bash by running !usr/bin/env bash

**Comment by Thunzhsh** [comment]
> Please give me the way to install DCNv2 on Google Colab. Thank you very much.

and for the  cpp file error, try check the version of pytorch

**Comment by bhumikasinghrk** [comment]
> Found this error while running demo.py file
> 
> `/content/drive/My Drive/FairMOT/src Traceback (most recent call last): File "demo.py", line 14, in <module> from track import eval_seq File "/content/drive/My Drive/FairMOT/src/track.py", line 15, in <module> from tracker.multitracker import JDETracker File "/content/drive/My Drive/FairMOT/src/lib/tracker/multitracker.py", line 8, in <module> from models.model import create_model, load_model File "/content/drive/My Drive/FairMOT/src/lib/models/model.py", line 8, in <module> from .networks.pose_dla_dcn import get_pose_net as get_dla_dcn File "/content/drive/My Drive/FairMOT/src/lib/models/networks/pose_dla_dcn.py", line 15, in <module> from .DCNv2.dcn_v2 import DCN File "/content/drive/My Drive/FairMOT/src/lib/models/networks/DCNv2/dcn_v2.py", line 13, in <module> import _ext as _backend ModuleNotFoundError: No module named '_ext'`

How did you solve this error? could you please specify?

**Comment by flashlau** [comment]
1. download https://github.com/jinfagang/DCNv2_latest
2. sudo python3 setup.py build develop
3. copy "dcn_v2.py" and “_ext.cpython-38-x86_64-linux-gnu.so” to FairMOT's sub-folder: src\lib\models\networks
