### ISSUE TITLE
There was a problem training on mot20, but it was normal on mot15

### ISSUE THREAD

**Issue by fuyuer233** [ifzhang/FairMOT#88]
@ifzhang while train mot20 ，its wrong。
```
mot/mot20_dla34Traceback (most recent call last):
  File "train.py", line 97, in <module>
    main(opt)
  File "train.py", line 68, in main
    log_dict_train, _ = trainer.train(epoch, train_loader)
  File "/home/user/CHENJIE/O/FairMOT-master/src/lib/trains/base_trainer.py", line 119, in train
    return self.run_epoch('train', epoch, data_loader)
  File "/home/user/CHENJIE/O/FairMOT-master/src/lib/trains/base_trainer.py", line 62, in run_epoch
    for iter_id, batch in enumerate(data_loader):
  File "/home/user/anaconda3/envs/env3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/user/anaconda3/envs/env3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/user/anaconda3/envs/env3.7/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/user/anaconda3/envs/env3.7/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/user/anaconda3/envs/env3.7/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/anaconda3/envs/env3.7/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/CHENJIE/O/FairMOT-master/src/lib/datasets/dataset/jde.py", line 456, in __getitem__
    wh[k] = 1. * w, 1. * h
IndexError: index 128 is out of bounds for axis 0 with size 128

```

**Comment by ifzhang** [comment]
When training on MOT20, you should set --K 500. It means the max number of objects in a frame. The original K is 128, but MOT20 has more than 128 objects in a frame, so you should set the max number 500 when training on MOT20.

**Comment by fuyuer233** [comment]
ok，thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yifu Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月4日(星期一) 晚上7:44
收件人:&nbsp;"ifzhang/FairMOT"<FairMOT@noreply.github.com&gt;;
抄送:&nbsp;"Fuyuer。"<1764588497@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ifzhang/FairMOT] There was a problem training on mot20, but it was normal on mot15 (#88)





 
When training on MOT20, you should set --K 500. It means the max number of objects in a frame. The original K is 128, but MOT20 has more than 128 objects in a frame, so you should set the max number 500 when training on MOT20.
